### PR TITLE
fix

### PR DESCRIPTION
**Pull request by johnletey**
Hiya @jakub-wojciechowski 👋🏻

Great project!

Was trying to use this, and there were some errors. I've gone ahead and fixed those 😄

### CODE REVIEW

**Comment by jakub-wojciechowski** [comment]
Hi @johnletey, great updates, thank you so much !!! 😄
The ar-gql package really simplifies a lot.
I've noticed that you removed the "Version" parameter from the query. At the moment, when the data schema is still under development, it's better to leave it there. The version increases with every breaking change and may be bumped up in the future.

**Comment by johnletey** [comment]
@jakub-wojciechowski Glad you like it 😄

Yeah, I did remove it as that's what was causing the error.

For some reason when you add that parameter to the GQL query, it errors.

We can talk more about it on Discord if you want. I'm `johnletey#1835`.

Might also be worth mentioning to the Arweave team 🤔

**Comment by jakub-wojciechowski** [comment]
@johnletey thank for your effort making the PR. I've merged it.
Right now I'll push the new version to the npm so it's operational again.  
Then, I'll try to debug why the "Version" tag causes the problem and let you know in Discord.

**Comment by johnletey** [comment]
@jakub-wojciechowski Sounds good 👍🏻

By the way, the error I get from GQL is:

> JSON Parse error: Unrecognized token '<'

**Pull request merged**
